language: minimal
sudo: required

addons:
  apt:
    packages:
      - sshfs

env:
  - ARCH=x86_64
  - ARCH=x86
  - ARCH=aarch64
  - ARCH=armhf
  - ARCH=ppc64le
  - ARCH=s390x

script:
  - ./travis.sh
