image: ubuntu
environment:
  DOCKER_PWD:
    secure: Lh+3bZX9Z9alhx3rj6EJv98AaSWob8wVeLeqp3Qb3HD2lJEhndqkq2o1WWAzLSXngQecEYQvzkvedue227Vgtw==
  matrix:
    - ARCH: x86_64
    - ARCH: x86
    - ARCH: aarch64
    - ARCH: armv7
    - ARCH: armhf
    - ARCH: ppc64le
    - ARCH: s390x
services:
  - docker
build_script:
  - sh: docker build -t ddosolitary/alpine-builder:$ARCH --build-arg ARCH=$ARCH .
  - sh: docker login -u ddosolitary -p "$DOCKER_PWD"
  - sh: docker push ddosolitary/alpine-builder:$ARCH
