on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, x86, aarch64, armv7, armhf, ppc64le, s390x]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - env:
          PRIVKEY: ${{ secrets.PRIVKEY }}
          S3FS_PWD: ${{ secrets.S3FS_PWD }}
          CI: true
          ARCH: ${{ matrix.arch }}
        run: ./run-docker.sh
